version: '3.8'

services:
  api:
    image: eduardokroetz/bloggig-api:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    sysctls:
      - net.core.somaxconn=511
      - vm.overcommit_memory=1  
    volumes:
      - redisdata:/data

volumes:
  redisdata:
